### ISSUE TITLE
GPU4PySCF v1.0 checklist

### ISSUE THREAD

**Issue by wxj6000** [pyscf/gpu4pyscf#159]
GPU4PySCF v1.0 will depend on PySCF v2.6.1

Release schedule: 
- [x] GPU4PySCF ~~v0.7.8~~ v0.7.9 (based on PySCF v2.5)
- [x] PySCF v2.6.0 (06/01/2024)
    - [x] PySCF v 2.6.1 w/ https://github.com/pyscf/pyscf/pull/2242 
- [x] GPU4PySCF ~~v0.7.9~~ v0.8.0 (based on PySCF v2.6)
    - [ ] (optional) Refactor int3c2e module, simplify `build` function and reorg `VHFOpt` attributes and methods.
    - [x] Replace dispersion correction with pyscf-dispersion. https://github.com/pyscf/gpu4pyscf/pull/163
    - [x] Support new DFT apis in PySCF v2.6. https://github.com/pyscf/pyscf/pull/2187 https://github.com/pyscf/gpu4pyscf/pull/163
    - [x] Support Numpy v2.0 https://github.com/pyscf/gpu4pyscf/pull/170
- [x]  GPU4PySCF v0.8.1
    - [x] Support dump GPU info to the PySCF log file. https://github.com/pyscf/gpu4pyscf/pull/165 
    - [x] Update the benchmark data. https://github.com/pyscf/gpu4pyscf/pull/165
- [x] GPU4PySCF v1.0

**Comment by sunqm** [comment]
I think the second point "Refactor int3c2e .." is not urgent. They are used internally only.

**Comment by wxj6000** [comment]
> I think the second point "Refactor int3c2e .." is not urgent. They are used internally only.

Yes. Its priority is low. We don't have to complete that one.
